# -*- coding: utf-8 -*-
"""CS328_DataScience_Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NXGj87NM7uZPiwZrRw2xjh8kFsrva4ah

# DataSet Explanation

We used datasets from two different sources to analyze the data nationally and internationally. We downloaded the data for India from the Ministry of Road Transport and Highways website in a comma-separated values format, which can be found here: https://morth.nic.in/road-accident-in-india. Similarly, we downloaded the data for all countries from the Organisation for Economic Co-operation and Development (OECD) website, which can be found here: https://data.oecd.org/transport/road-accidents.htm. However, we altered the columns and rows of both datasets to make them more usable.


In the first dataset, one column is for the years between 2006-2020, another for the number of fatalities, and other columns are for the number of injuries and the type of accident caused. The second dataset has the first column for the different country names, the second for the number of deaths in that specific country in that year, and other columns for Country Codes and years from 2006-2021. The first dataset includes statistics on the proportion of road accident casualties through time for fatalities and injuries. The second dataset is based on the total number of deaths in different countries over the past years. We used the Country Codes of different countries in this data to show the bottom-most visualization below (Circles on the natural earth). For a given year and nation, each cell would have the value corresponding to that category. However, we could only access data for the years from 2006-2021 and categories for each nation, so we only included those in our analysis.
"""

import plotly.express as px
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Loading the CSV file
df = pd.read_csv('/content/Deaths and Injuries Over the period of 2006-2020 - Sheet1 (1).csv', skiprows=1)

# Loop to iterate and generate seperate pie charts
for year in df['year']:
    # Filter to include only year
    year_df = df[df['year'] == year].copy()


    # print(year_df.ratio)
    # print(year_df.shape)

    year_df.loc[:, 'fatility rate'] = pd.to_numeric(year_df['fatility rate'])
    year_df.loc[:, 'injuries'] = pd.to_numeric(year_df['injuries'])

    # Calculating the percentages of fatalities and injuries
    fatality_percent = year_df['fatility rate'] / (year_df['fatility rate'] + year_df['injuries']) * 100
    injury_percent = year_df['injuries'] / (year_df['fatility rate'] + year_df['injuries']) * 100


    y = np.array([fatality_percent, injury_percent])
    mylabels = ["Fatality", "Injuries"]
    fig, ax = plt.subplots(figsize=(5, 4))
    fig.set_facecolor('white')
    explode = (0.1, 0)
    ax.pie(np.squeeze(y), labels=mylabels, autopct='%1.1f%%', explode=explode, shadow=True)
    ax.set_title("Fatality vs Injuries " + str(year))
    plt.show()

"""Each pie chart depicts the percentage value of Fatalities and Injuries caused due to road accidents in each year throughout India during the period of 2006-2020. This component was calculated by first adding the total number of Fatalities and total number of Injuries during that specific year and used this number to compute the different percentages of Fatalities and Injuries. 

Over the period of 2006-2020, India has seen a significant increase in the total number of road accidents. In 2006, around 18% of all persons involved in road accidents in India were fatality cases. However, fatality cases accounted for around 24% of all road accident cases in 2016. This change can be attributed to several factors, including the increase in the number of vehicles on the road, the lack of proper infrastructure, and the failure to implement traffic laws and regulations effectively.

The number of fatalities and injuries increased from 2006 to 2016 and then decreased in the following years. The year 2020 had the lowest number of fatalities and injuries compared to the other years in the data.

To visualize the data, we can create line plots for fatalities and injuries against the years.
"""

import plotly.express as px
import pandas as pd

# Data
df = pd.read_csv('/content/Deaths and Injuries Over the period of 2006-2020 - Sheet1 (1).csv', skiprows=1)

# line plot for fatalities over years
fig = px.line(df, x='year', y='fatility rate', title='Number of fatalities due to road accidents')
fig.update_traces(marker=dict(size=5, symbol='circle-open-dot'))
fig.show()

# mean_value = df['injuries'].mean()
# df['injuries'].fillna(value=mean_value, inplace=True)

# line plot for injuries
fig = px.line(df, x='year', y='injuries', title='Number of injuries due to road accidents')
fig.update_traces(marker=dict(size=5, symbol='circle-open-dot'))
fig.show()

"""**Hypothesis:** The number of fatalities due to road accidents decreased in recent years.

**Quantification:** We can compare the average number of fatalities in the first 5 years (2006-2010) and the last 5 years (2016-2020) of the data to test the hypothesis. We can use a two-sample t-test to compare the means of the two groups.
"""

from scipy.stats import ttest_ind

# Data for the two groups
fatalities_2006_2010 = [105749, 114444, 119860, 125660, 134513]
fatalities_2016_2020 = [150785, 147913, 151417, 151113, 131714]


# t-test
t, p = ttest_ind(fatalities_2006_2010, fatalities_2016_2020)

print('t =', t)
print('p-value =', p)

"""Since the p-value is less than 0.05, we reject the null hypothesis that the two groups have the same mean. Therefore, we can conclude that the number of fatalities due to road accidents decreased in recent years.

*Let's look into another hypothesis,*

**Hypothesis:** There is a correlation between the number of fatalities and injuries due to road accidents.

To quantify the hypothesis, we can calculate the correlation coefficient between the number of fatalities and injuries. A correlation coefficient is a measure of the strength and direction of the linear relationship between two variables.

We can use the Pearson correlation coefficient, which measures the linear correlation between two variables, to quantify the hypothesis. The Pearson correlation coefficient ranges from -1 to 1, where -1 indicates a perfect negative correlation, 0 indicates no correlation, and 1 indicates a perfect positive correlation.

Here's the code to calculate the Pearson correlation coefficient using Python:
"""

import pandas as pd

# Data
df = pd.read_csv('/content/Deaths and Injuries Over the period of 2006-2020 - Sheet1 (1).csv', skiprows=1)

# print(df.shape)
# print(df.ratio)


# Calculating the Pearson correlation coefficient
corr_coeff = df['fatility rate'].corr(df['injuries'], method='pearson')

print('Pearson correlation coefficient:', corr_coeff)

"""The Pearson correlation coefficient is -0.197, which indicates a weak negative correlation between the number of fatalities and injuries due to road accidents. However, it is important to note that correlation does not imply causation, and other factors may be contributing to the relationship between these variables. Therefore, further analysis is required to fully understand the relationship between fatalities and injuries due to road accidents. We would like to skip these deep analyses here. """

import pandas as pd
import plotly.express as px

# Read the data from a CSV file
df = pd.read_csv("/content/Worldwide Deaths due to Road Accidents - Sheet1 (2).csv")

# mean_value = df['Deaths'].mean()
# df['Deaths'].fillna(value=mean_value, inplace=True)

# mean_value = df['Country COde'].mean()
# df['Deaths'].fillna(value=mean_value, inplace=True)

# mean_value = df['Deaths'].mean()
# df['Country COde'].fillna(value=mean_value, inplace=True)



# print(df.shape)
# print(df.ratio)
fig = px.scatter_geo(df, locations="Country Code", size="Deaths", animation_frame="YEAR",
                     projection="natural earth", color="Country Name", hover_name="Country Name",
                     size_max=50, template="plotly_dark")



fig.update_layout(title="Road Accidents for Different Countries over Years", margin={"r":0,"t":0,"l":0,"b":0})

# Displaying the Final Plot 
fig.show()

"""The scatter geo plot above depicts the number of deaths that took place in different countries due to road accidents from 2006 to 2021. The size of the circles represents the number of deaths in that country, with larger circles indicating higher numbers of deaths. The plot clearly shows that countries in Asia, particularly India and China, have a significantly higher number of deaths due to road accidents compared to other countries. One of the major reasons is the lack of proper infrastructure and safety measures on the roads. Many roads in these countries are poorly constructed and lack safety features like barriers, streetlights, and speed limits. Moreover, many drivers in these countries do not follow traffic rules and often indulge in reckless driving, leading to accidents. Another reason is the high population density in these countries, which leads to more traffic on the roads and consequently a higher number of accidents.

India, in particular, has consistently registered a high number of deaths due to road accidents over the past 15 years, with the numbers never dropping below one lakh. In contrast, many European countries, such as Liechtenstein, Iceland, and Malta, have never recorded more than 50 deaths in a year due to road accidents. This can be attributed to the high level of safety measures implemented on their roads. These countries have well-maintained roads, proper traffic rules and regulations, and efficient emergency services. Additionally, these countries have a low population density, leading to less traffic on their roads and fewer accidents. The high number of cases in India can also be attributed to the country's large population and the lack of awareness among people about road safety measures. Moreover, the poor condition of public transport in the country forces people to rely on personal vehicles for commuting, which further increases traffic on the roads and the risk of accidents.



The data also shows the reduction in the number of deaths due to road accidents in countries like the USA, Russia, and China. This can be attributed to the implementation of stringent traffic rules and regulations, along with the use of advanced technologies like automated traffic control systems, speed cameras, and better emergency services. Moreover, awareness campaigns have been launched in these countries to educate people about road safety measures, leading to a positive impact on the number of accidents.


In conclusion, road safety is a crucial issue that needs to be addressed globally. The high number of deaths due to road accidents in some countries can be attributed to various factors like poor infrastructure, lack of awareness, and high population density. Governments need to implement stringent rules and regulations to ensure road safety, along with educating people about the importance of following traffic rules and regulations. Advanced technologies like automated traffic control systems and speed cameras should also be implemented to reduce the number of accidents. Ultimately, the safety of the roads is a collective responsibility, and everyone needs to do their part to ensure that our roads are safe for everyone.


"""